# ========================================
# Redis Configuration (Default/Production)
# ========================================
# Redisson client configuration for distributed lock
# Environment variables are injected via ECS Task Definition
# ========================================

spring:
  data:
    redis:
      # Redis Server
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      # password는 REDIS_PASSWORD 환경변수가 설정된 경우에만 사용
      # ElastiCache는 기본적으로 AUTH 없이 동작
      database: ${REDIS_DATABASE:0}

      # Connection timeout
      timeout: 3000ms
      connect-timeout: 3000ms

# ========================================
# Redisson Configuration
# ========================================
redisson:
  # Single server mode (Production: Use Cluster or Sentinel)
  single-server-config:
    address: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
    # password는 REDIS_PASSWORD 환경변수가 설정된 경우에만 사용
    # ElastiCache는 기본적으로 AUTH 없이 동작
    database: ${REDIS_DATABASE:0}

    # Connection Pool
    connection-minimum-idle-size: 5
    connection-pool-size: 20

    # Timeout
    connect-timeout: 3000
    timeout: 3000
    retry-attempts: 3
    retry-interval: 1500

    # Subscription
    subscription-connection-minimum-idle-size: 1
    subscription-connection-pool-size: 5

  # Thread Pool
  threads: 4
  netty-threads: 4

# ========================================
# Distributed Lock Configuration
# ========================================
distributed-lock:
  # Default lock settings
  default-wait-time-ms: 5000
  default-lease-time-ms: 30000

  # Lock key prefixes
  key-prefix: "crawlinghub:lock:"

  # Specific lock configurations
  crawl-trigger:
    wait-time-ms: 3000
    lease-time-ms: 60000

  crawl-task:
    wait-time-ms: 5000
    lease-time-ms: 300000

# ========================================
# UserAgent Pool Configuration
# ========================================
useragent-pool:
  # Rate Limiting (Sliding Window)
  rate-limit:
    # 시간당 최대 요청 수
    max-tokens: 80
    # 윈도우 지속 시간 (ISO-8601 Duration: PT1H = 1시간)
    window-duration: PT1H

  # Session Management
  session:
    # 선제적 세션 갱신 버퍼 (분)
    # 세션 만료 N분 전에 갱신 시작
    renewal-buffer-minutes: 5

  # Health Score
  health:
    # SUSPENDED로 전환되는 최소 점수
    suspension-threshold: 30

  # Key Prefixes
  key-prefix: "useragent:"

logging:
  level:
    org.redisson: INFO
