# ============================================================
# Redis Layer 공통 설정
# ============================================================
# 환경별 설정은 redis-{profile}.yml 참조
# - redis-local.yml: 로컬 개발 환경
# - redis-stage.yml: 스테이징 환경
# - redis-prod.yml: 운영 환경
# ============================================================

spring:
  data:
    redis:
      timeout: 3000ms
      connect-timeout: 3000ms

# ============================================================
# Distributed Lock Configuration
# ============================================================
distributed-lock:
  default-wait-time-ms: 5000
  default-lease-time-ms: 30000
  key-prefix: "crawlinghub:lock:"

  crawl-trigger:
    wait-time-ms: 3000
    lease-time-ms: 60000

  crawl-task:
    wait-time-ms: 5000
    lease-time-ms: 300000

# ============================================================
# UserAgent Pool Configuration
# ============================================================
useragent-pool:
  rate-limit:
    max-tokens: 80
    window-duration: PT1H

  session:
    renewal-buffer-minutes: 5

  health:
    suspension-threshold: 30

  key-prefix: "useragent:"
