# ============================================================
# Redis Layer 스테이징 환경 설정
# ============================================================
# 활성화: spring.profiles.active=stage
# ============================================================

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}

logging:
  level:
    org.redisson: INFO
