# ============================================================
# Redis Layer 로컬 개발 환경 설정
# ============================================================
# 활성화: spring.profiles.active=local
# docker run -d --name redis -p 6379:6379 redis:7-alpine
# ============================================================

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    org.redisson: DEBUG
