# ========================================
# SQS Listener Configuration (Default/Production)
# ========================================
# Spring Cloud AWS SQS configuration
# Environment variables are injected via ECS Task Definition
# ========================================

spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      sqs:
        # SQS 리스너 기본 설정
        listener:
          max-concurrent-messages: 10
          max-messages-per-poll: 10

aws:
  sqs:
    listener:
      # ========================================
      # Queue URLs (from Terraform SSM Parameters)
      # ========================================
      # CrawlTask Queue: receives tasks from aws-sqs module
      crawl-task-queue-url: ${SQS_CRAWL_TASK_QUEUE_URL:}

      # EventBridge Trigger Queue: receives scheduler triggers
      event-bridge-trigger-queue-url: ${SQS_EVENTBRIDGE_TRIGGER_QUEUE_URL:}

      # CrawlTask DLQ: receives failed tasks for error handling
      crawl-task-dlq-url: ${SQS_CRAWL_TASK_DLQ_URL:}

      # ========================================
      # Feature Toggles
      # ========================================
      # Enable/Disable individual listeners
      crawl-task-listener-enabled: true
      event-bridge-trigger-listener-enabled: true
      crawl-task-dlq-listener-enabled: true

logging:
  level:
    com.ryuqq.crawlinghub.adapter.in.sqs: INFO
    io.awspring.cloud.sqs: INFO
