# ========================================
# HTTP Client Configuration
# ========================================
# Session token issuance HTTP client settings
# Used for external site access to obtain session cookies

http-client:
  session:
    # Target URL for session token issuance
    target-url: https://m.web.mustit.co.kr/
    # Session cookie name to extract (mustit uses JWT token)
    session-cookie-name: token
    # Connection timeout in seconds
    connect-timeout: 10
    # Request timeout in seconds
    request-timeout: 30
    # Default session duration in hours (when expires not provided)
    default-session-duration-hours: 2

---
# ========================================
# Local Profile
# ========================================
spring:
  config:
    activate:
      on-profile: local

http-client:
  session:
    target-url: https://m.web.mustit.co.kr/
    connect-timeout: 10
    request-timeout: 30

---
# ========================================
# Production Profile
# ========================================
spring:
  config:
    activate:
      on-profile: prod

http-client:
  session:
    target-url: https://m.web.mustit.co.kr/
    connect-timeout: 5
    request-timeout: 15
