# ============================================================
# Persistence Layer 스테이징 환경 설정
# ============================================================
# 활성화: spring.profiles.active=stage
# ============================================================

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

      leak-detection-threshold: 60000

      pool-name: CrawlingHub-HikariPool-Stage

      connection-init-sql: SELECT 1

      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  flyway:
    clean-disabled: true
    validate-on-migrate: false

logging:
  level:
    com.ryuqq.crawlinghub: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
